# fly.toml app configuration file generated for tuttibot on 2026-02-23T20:07:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tuttibot"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  app = "python main.py"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
